# slam_toolbox:
#   ros__parameters:
#     map_frame: map
#     odom_frame: odom
#     base_frame: base_link
#     laser_frame: taitc_lidar_link   
#     scan_topic: /scan
#     odom_topic: /odom
#     mode: mapping
#     autostart: true
#     use_scan_matching: true
#     provide_odom_frame: true
#     transform_tolerance: 0.2       
#     sensor_queue_size: 100
#     max_laser_scan_queue_size: 100
#     minimum_time_interval: 0.5    
#     map_update_interval_sec: 1.0   
#     publish_period_sec: 0.5 
#     resolution: 0.05               
#     max_laser_range: 8.0            
#     min_laser_range: 0.12           
#     optimize_every_n_nodes: 10
#     max_likelihood_score: 0.7
#     use_sim_time: false
    

slam_toolbox:
  ros__parameters:
    use_sim_time: false

    # Frames
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    odom_topic: /odom

    # Mapping mode
    mode: mapping
    publish_tf: true
    resolution: 0.05
    map_update_interval: 1.0  # Faster updates
    transform_publish_period: 0.05
    minimum_time_interval: 0.1

    # Scan matching and filtering
    use_scan_matching: true
    use_map_scan_matching: true
    scan_queue_size: 10
    map_queue_size: 10
    max_laser_range: 8.0
    minimum_laser_range: 0.12
    loop_closure_maximum_distance: 1.0
    loop_closure_minimum_time_interval: 15.0
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.017

    # Optimization and smoothing
    smoothing_factor: 0.02
    do_loop_closing: true
    loop_closure_frequency: 0.5
    use_response_expansion: true
    use_correlative_scan_matching: false

    # Map persistence
    map_save_period: 60.0
    always_send_full_map: false

    # Debugging/logging
    debug_logging: false
    throttle_scans: 1

# slam_toolbox:
#   ros__parameters:
#     use_sim_time: false
#     odom_frame: odom
#     map_frame: map
#     base_frame: base_link
#     scan_topic: /scan
#     odom_topic: /odom
#     # laser_frame: taitc_lidar_link 
#     resolution: 0.05
#     transform_publish_period: 0.05
#     minimum_time_interval: 0.05
#     mode: mapping
#     map_update_interval: 1.0
#     publish_tf: true

#     loop_closure:
#       min_score: 0.6

#     use_scan_matching: true
#     scan_queue_size: 40
#     queue_size: 10

#     scan_matcher:
#       linear_search_window: 0.5
#       angular_search_window: 0.3
#       translation_weight: 1.0
#       rotation_weight: 1.0





# slam_toolbox:
#   ros__parameters:
#     use_sim_time: false
#     odom_frame: odom
#     map_frame: map
#     base_frame: base_link
#     scan_topic: /scan
#     # Commonly useful params
#     resolution: 0.05
#     transform_publish_period: 0.05
#     minimum_time_interval: 0.1
#     mode: mapping
