slam_toolbox:
  ros__parameters:
    use_sim_time: false
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    resolution: 0.05
    transform_publish_period: 0.05
    minimum_time_interval: 0.1
    mode: mapping
    map_update_interval: 2.0
    publish_tf: true


# slam_toolbox:
#   ros__parameters:
#     use_sim_time: false
#     odom_frame: odom
#     map_frame: map
#     base_frame: base_link
#     scan_topic: /scan
#     # Commonly useful params
#     resolution: 0.05
#     transform_publish_period: 0.05
#     minimum_time_interval: 0.1
#     mode: mapping
