# slam_toolbox:
#   ros__parameters:
#     map_frame: map
#     odom_frame: odom
#     base_frame: base_link
#     laser_frame: taitc_lidar_link   
#     scan_topic: /scan
#     odom_topic: /odom
#     mode: mapping
#     autostart: true
#     use_scan_matching: true
#     provide_odom_frame: true
#     transform_tolerance: 0.2       
#     sensor_queue_size: 100
#     max_laser_scan_queue_size: 100
#     minimum_time_interval: 0.5    
#     map_update_interval_sec: 1.0   
#     publish_period_sec: 0.5 
#     resolution: 0.05               
#     max_laser_range: 8.0            
#     min_laser_range: 0.12           
#     optimize_every_n_nodes: 10
#     max_likelihood_score: 0.7
#     use_sim_time: false
    


slam_toolbox:
  ros__parameters:
    use_sim_time: false
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    odom_topic: /odom
    # laser_frame: taitc_lidar_link 
    resolution: 0.05
    transform_publish_period: 0.05
    minimum_time_interval: 0.1
    mode: mapping
    map_update_interval: 2.0
    publish_tf: true

    use_scan_matching: true
    scan_queue_size: 10
    queue_size: 10



# slam_toolbox:
#   ros__parameters:
#     use_sim_time: false
#     odom_frame: odom
#     map_frame: map
#     base_frame: base_link
#     scan_topic: /scan
#     # Commonly useful params
#     resolution: 0.05
#     transform_publish_period: 0.05
#     minimum_time_interval: 0.1
#     mode: mapping
